require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WorkEntriesController do

  # This should return the minimal set of attributes required to create a valid
  # WorkEntry. As you add validations to WorkEntry, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all work_entries as @work_entries" do
      work_entry = WorkEntry.create! valid_attributes
      get :index
      assigns(:work_entries).should eq([work_entry])
    end
  end

  describe "GET show" do
    it "assigns the requested work_entry as @work_entry" do
      work_entry = WorkEntry.create! valid_attributes
      get :show, :id => work_entry.id.to_s
      assigns(:work_entry).should eq(work_entry)
    end
  end

  describe "GET new" do
    it "assigns a new work_entry as @work_entry" do
      get :new
      assigns(:work_entry).should be_a_new(WorkEntry)
    end
  end

  describe "GET edit" do
    it "assigns the requested work_entry as @work_entry" do
      work_entry = WorkEntry.create! valid_attributes
      get :edit, :id => work_entry.id.to_s
      assigns(:work_entry).should eq(work_entry)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WorkEntry" do
        expect {
          post :create, :work_entry => valid_attributes
        }.to change(WorkEntry, :count).by(1)
      end

      it "assigns a newly created work_entry as @work_entry" do
        post :create, :work_entry => valid_attributes
        assigns(:work_entry).should be_a(WorkEntry)
        assigns(:work_entry).should be_persisted
      end

      it "redirects to the created work_entry" do
        post :create, :work_entry => valid_attributes
        response.should redirect_to(WorkEntry.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved work_entry as @work_entry" do
        # Trigger the behavior that occurs when invalid params are submitted
        WorkEntry.any_instance.stub(:save).and_return(false)
        post :create, :work_entry => {}
        assigns(:work_entry).should be_a_new(WorkEntry)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        WorkEntry.any_instance.stub(:save).and_return(false)
        post :create, :work_entry => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested work_entry" do
        work_entry = WorkEntry.create! valid_attributes
        # Assuming there are no other work_entries in the database, this
        # specifies that the WorkEntry created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        WorkEntry.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => work_entry.id, :work_entry => {'these' => 'params'}
      end

      it "assigns the requested work_entry as @work_entry" do
        work_entry = WorkEntry.create! valid_attributes
        put :update, :id => work_entry.id, :work_entry => valid_attributes
        assigns(:work_entry).should eq(work_entry)
      end

      it "redirects to the work_entry" do
        work_entry = WorkEntry.create! valid_attributes
        put :update, :id => work_entry.id, :work_entry => valid_attributes
        response.should redirect_to(work_entry)
      end
    end

    describe "with invalid params" do
      it "assigns the work_entry as @work_entry" do
        work_entry = WorkEntry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WorkEntry.any_instance.stub(:save).and_return(false)
        put :update, :id => work_entry.id.to_s, :work_entry => {}
        assigns(:work_entry).should eq(work_entry)
      end

      it "re-renders the 'edit' template" do
        work_entry = WorkEntry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WorkEntry.any_instance.stub(:save).and_return(false)
        put :update, :id => work_entry.id.to_s, :work_entry => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested work_entry" do
      work_entry = WorkEntry.create! valid_attributes
      expect {
        delete :destroy, :id => work_entry.id.to_s
      }.to change(WorkEntry, :count).by(-1)
    end

    it "redirects to the work_entries list" do
      work_entry = WorkEntry.create! valid_attributes
      delete :destroy, :id => work_entry.id.to_s
      response.should redirect_to(work_entries_url)
    end
  end

end
